# Generated by Django 3.0.8 on 2020-07-10 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phoneregister', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='otp',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='myuser',
            name='otp_create_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
