# Generated by Django 3.0.8 on 2020-07-10 18:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phoneregister', '0003_auto_20200710_2204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='otp_create_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 10, 22, 56, 7, 620197)),
        ),
    ]
