# Generated by Django 3.0.8 on 2020-07-10 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phoneregister', '0004_auto_20200710_2256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='otp_create_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
